name: build

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo OS version
        run: echo "the buid is successful"
